# For parameter descriptions, please refer to the template parameter files for each node.

ekf_filter_node_odom:
  ros__parameters:
    frequency: 5.0
    sensor_timeout: 0.1
    two_d_mode: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: true 
    #debug_out_file: /home/jakub/Documents/RTAB-Map/src/my_rtabmap/launch/debug.txt
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /odom_rgbd
    odom0_config: [true, true, true,
                  true, true, true,
                  false,  false,  false,
                  false,  false,  false,
                  false, false, false]
    odom0_queue_size: 10
    odom0_differential: true
    odom0_relative: true

    imu0: /mavros/imu/data_raw
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    use_control: false

ekf_filter_node_map:
  ros__parameters:
    frequency: 5.0
    sensor_timeout: 0.1
    two_d_mode: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    odom0: /odom_rgbd
    odom0_config: [true, true, true,
                  true, true, true,
                  false,  false,  false,
                  false,  false,  false,
                  false, false, false]
    odom0_queue_size: 10
    odom0_differential: true
    odom0_relative: true

    odom1: odometry/gps
    odom1_config: [true,  true,  true,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: true

    imu0: /mavros/imu/data_raw
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
    
    use_control: false

navsat_transform:
  ros__parameters:
    frequency: 5.0
    yaw_offset: 0.0
    zero_altitude: false
    broadcast_cartesian_transform: true
    wait_for_datum: true
    datum: [44.937015388333336, 9.450198341666667, 4.855679579752934]